[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "scripts"
solc = "0.8.28"
viaIR = true
fs_permissions = [{ access = "read-write", path = "./"}]
ffi = true
allow_internal_expect_revert = true
optimizer = true
optimizer_runs = 10000

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@uniswap-v2/v2-periphery/=lib/v2-periphery/contracts/",
    "@solady/src/=lib/solady/src/",
    "forge-std/=lib/forge-std/src/",
    "@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/",
    "@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/",
    "@layerzerolabs/oapp-evm-upgradeable/=lib/devtools/packages/oapp-evm-upgradeable/",
    "@layerzerolabs/lz-evm-oapp-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/",
    '@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/'
]

no_match_test = "test_skip"

additional_compiler_profiles = [
    { name = "big_contracts", optimizer_runs = 900, via_ir = true, optimizer = true },
]

compilation_restrictions = [
    { paths = "src/facets/VaultFacet.sol", optimizer_runs = 900 },
    { paths = "src/factory/VaultsFactory.sol", optimizer_runs = 900 },
]

[profile.local_e2e]
code_size_limit = 30000

[rpc_endpoints]
flow_testnet = "${FLOW_TESTNET_RPC_URL}"
